StylesPath = styles
MinAlertLevel = suggestion

# Example house rules; add, remove, or tweak as you like
[*.md, *.mdx]
BasedOnStyles = Google

# Disable passive-voice checks in code blocks
[code]
  passiv = NO
