StylesPath = .github/workflows/vale-styles

MinAlertLevel = suggestion

[formats]
mdx = md

[*.{md,mdx}]
BasedOnStyles = Vale, write-good, Microsoft

# Custom rules
Vale.Terms = YES
Vale.Avoid = YES
write-good.ThereIs = YES
write-good.TooWordy = YES
write-good.Weasel = YES
write-good.Passive = YES
Microsoft.Contractions = NO
Microsoft.FirstPerson = NO
Microsoft.We = NO
